# -*- coding: utf-8 -*-
"""typing speed .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mb93AynmZbjk3OqutA6mjxndwsloh04e
"""

import time
import random

# List of sentences to type
sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Python programming is both fun and challenging.",
    "Typing fast requires practice and patience.",
    "Machine learning is transforming the world.",
    "Data science involves both statistics and programming."
]

def typing_test():
    # Select a random sentence
    sentence = random.choice('Coding is fun')
    print("Type the following sentence as quickly as you can:")
    print(sentence)

    # Wait for user to start typing
    input("Press Enter to start...")

    # Record start time
    start_time = time.time()
    # Get user's input
    typed_sentence = input("Type here: ")
    # Record end time
    end_time = time.time()

    # Calculate elapsed time
    elapsed_time = end_time - start_time
    elapsed_minutes = elapsed_time / 60

    # Calculate words per minute (WPM)
    word_count = len(sentence.split())
    accuracy = len([i for i, j in zip(sentence, typed_sentence) if i == j]) / len(sentence) * 100
    wpm = word_count / elapsed_minutes

    print("\nResults:")
    print(f"Time taken: {elapsed_time:.2f} seconds")
    print(f"Words per minute (WPM): {wpm:.2f}")
    print(f"Accuracy: {accuracy:.2f}%")

# Run the typing test
typing_test()